server:
  port: 9006
  
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type: DEBUG
  path: /logs
  file: ${logging.path}${server.servlet.context-path}/application_test.log 
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    
#API connect REST END POINTS

#REST Endpoints configuration
api:
 endpoints:
   createOrder:
     path: /abs/sb/v1/OFIP/orderService/createOrder
     method: post
     location: https://api-dvint.albertsons.com
   getOrderStatus:
     path: /abs/sb/v1/OFIP/orderService/createOrder
     method: post
     location: https://api-dvint.albertsons.com
 header:
  x-ibm-client-id: d12c4456-9454-476f-88e4-cc80eb7d6b1c
  x-ibm-client-secret: oS1jF6xR4xH4oD0wS5pM4bJ8xL3eY2rQ8uM7vT3aC2uW7lV7qG
        

# JDBC Url to use H2 DB File for persisting
spring:
  datasource:
    url: jdbc:h2:mem:ofip-orderservice-test1;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driverClassName: org.h2.Driver
    initialization-mode: always
    continue-on-error: true 
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        session_factory:
         interceptor: com.safeway.ofip.commons.repository.CustomEntityInterceptor
      javax:
        persistence:
          schema-generation:
            create-source: metadata 
    show-sql: true
    database: MySQL
    generate-ddl: true
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      write_dates_as_timestamps: false
