server:
  port: 9006

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type: DEBUG
  path: /logs
  file: ${logging.path}${server.servlet.context-path}/application.log 
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"