server:
  port: 9008
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
    continue-on-error: false 
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  thymeleaf:
    cache: false
  jackson:
    serialization:
      write_dates_as_timestamps: false